import Hesper
import Hesper.Models.Gemma4
import Hesper.WebGPU.Device
import Hesper.WebGPU.Buffer
import Hesper.WebGPU.BufferOps
import Hesper.Validation.Metrics
import Hesper.Validation.ReferenceData

/-!
# Gemma 4 Validation Against llama-cpp-python Golden Values

Loads reference logits from Tests/golden-values-gemma4/ (generated by
scripts/generate_gemma4_golden.py) and compares Hesper's single-token
forward pass output against them.

Usage:
  python3 scripts/generate_gemma4_golden.py data/gemma-4-e4b-it-Q4_K_M.gguf
  lake exe gemma4-validation
-/

open Hesper.WebGPU
open Hesper.Validation.Metrics
open Hesper.Validation.ReferenceData

def loadInputTokens (path : String) : IO (Array Nat) := do
  let bytes ← IO.FS.readBinFile path
  let mut tokens := #[]
  for i in [0:(bytes.size / 4)] do
    let offset := i * 4
    let b0 := bytes.get! offset |>.toUInt32
    let b1 := bytes.get! (offset + 1) |>.toUInt32
    let b2 := bytes.get! (offset + 2) |>.toUInt32
    let b3 := bytes.get! (offset + 3) |>.toUInt32
    let tokenId := (b0 ||| (b1 <<< 8) ||| (b2 <<< 16) ||| (b3 <<< 24)).toNat
    tokens := tokens.push tokenId
  return tokens

def main (args : List String) : IO Unit := do
  let modelPath := args.getD 0 "data/gemma-4-e4b-it-Q4_K_M.gguf"
  let dataDir := args.getD 1 "Tests/golden-values-gemma4"

  IO.println "═══════════════════════════════════════════════"
  IO.println "  Gemma 4 Validation vs llama-cpp-python"
  IO.println "═══════════════════════════════════════════════"
  IO.println s!"  Model: {modelPath}"
  IO.println s!"  Golden values dir: {dataDir}"
  IO.println ""

  -- Load input tokens
  IO.println "[1/5] Loading input tokens..."
  let inputTokens ← loadInputTokens (dataDir ++ "/input_tokens.bin")
  IO.println s!"  Loaded {inputTokens.size} tokens: {inputTokens}"

  -- Initialize WebGPU
  IO.println "[2/5] Initializing WebGPU..."
  let inst ← Hesper.init
  let device ← Hesper.WebGPU.getDevice inst
  IO.println "  Device initialized"

  -- Load Gemma 4 model
  IO.println "[3/5] Loading Gemma 4 model..."
  let model ← Hesper.Models.Gemma4.Gemma4Model.fromGGUF device modelPath
  IO.println s!"  Model: {model.config.numHiddenLayers} layers, {model.config.hiddenSize} dim, vocab={model.config.vocabSize}"

  -- Run Hesper forward pass for each prompt token, keeping last logits
  IO.println "[4/5] Running Hesper forward pass..."
  let state ← Hesper.Models.Gemma4.createInferenceState device model.config
  let mut pos := 0
  for tok in inputTokens do
    Hesper.Models.Gemma4.forwardSingleToken device model tok pos state
    pos := pos + 1
  IO.println "  Forward pass complete"

  -- DEBUG: sample buf1 and buf2 to see intermediate state
  let buf1Data ← Hesper.WebGPU.BufferOps.downloadFloatArray device state.buf1 16
  IO.println s!"  [debug] buf1 first 8: {buf1Data.toList.take 8}"
  let buf2Data ← Hesper.WebGPU.BufferOps.downloadFloatArray device state.buf2 16
  IO.println s!"  [debug] buf2 first 8: {buf2Data.toList.take 8}"
  let normedData ← Hesper.WebGPU.BufferOps.downloadFloatArray device state.normedBuf 16
  IO.println s!"  [debug] normedBuf first 8: {normedData.toList.take 8}"

  -- Download Hesper logits
  let hesperLogits ← Hesper.WebGPU.BufferOps.downloadFloatArray device state.logitsBuf model.config.vocabSize
  IO.println s!"  Downloaded {hesperLogits.size} logits"

  -- Find Hesper's argmax
  let mut maxVal := hesperLogits[0]!
  let mut maxIdx := 0
  for i in [0:hesperLogits.size] do
    let v := hesperLogits[i]!
    if v > maxVal then
      maxVal := v
      maxIdx := i
  IO.println s!"  Hesper argmax: token {maxIdx} = {maxVal}"

  -- Load golden logits
  IO.println "[5/5] Comparing against golden values..."
  let goldenLogits ← loadFloatArrayFromFile (dataDir ++ "/logits_output.bin")
  IO.println s!"  Golden logits size: {goldenLogits.size}"

  -- Find golden argmax
  let mut gMaxVal := goldenLogits[0]!
  let mut gMaxIdx := 0
  for i in [0:goldenLogits.size] do
    let v := goldenLogits[i]!
    if v > gMaxVal then
      gMaxVal := v
      gMaxIdx := i
  IO.println s!"  Golden argmax: token {gMaxIdx} = {gMaxVal}"

  if goldenLogits.size != hesperLogits.size then
    IO.println s!"  ❌ Size mismatch: Hesper={hesperLogits.size}, Golden={goldenLogits.size}"
    return

  -- Print first 10 logits side by side
  IO.println ""
  IO.println "  First 10 logits comparison:"
  IO.println "  idx | Hesper           | Golden           | Diff"
  IO.println "  ----+------------------+------------------+----------------"
  for i in [0:10] do
    let h := hesperLogits[i]!
    let g := goldenLogits[i]!
    let d := h - g
    IO.println s!"  {i} | H={h} | G={g} | diff={d}"

  -- Compute validation report
  let report := generateReport goldenLogits hesperLogits 1e-2
  IO.println ""
  IO.println "  === Validation Report ==="
  printReport report

  -- Match check
  IO.println ""
  if maxIdx == gMaxIdx then
    IO.println s!"  ✅ Argmax matches: {maxIdx}"
  else
    IO.println s!"  ❌ Argmax mismatch: Hesper={maxIdx}, Golden={gMaxIdx}"

  IO.println ""
  IO.println "Done!"
