import Hesper
import Hesper.TTT.Types
import Hesper.TTT.Kernels
import Hesper.TTT.InnerLoop
import Hesper.TTT.Layer
import Hesper.TTT.Init
import Hesper.Validation.ReferenceData
import Hesper.Validation.Metrics
import Hesper.WebGPU.Device
import Lean.Data.Json
import Lean.Data.Json.Parser

/-!
# TTT Golden Value GPU Test Runner

Loads golden values generated by `hesper-ttt/scripts/ttt_golden_gen.py`
and compares against the GPU TTT implementation. Reads config from
metadata.json to support any sequence length.

Port of `hesper-ttt/Tests/TTT/TTTGoldenMain.lean` — same validation
logic, but running on GPU via Hesper.TTT.*.
-/

open Hesper.TTT
open Hesper.Validation.ReferenceData
open Hesper.Validation.Metrics
open Hesper.WebGPU

/-- Parse a JSON number as Nat -/
def jsonToNat (j : Lean.Json) (key : String) : IO Nat := do
  match j.getObjValAs? Lean.Json key with
  | .ok val =>
    match val.getNat? with
    | .ok n => return n
    | .error _ =>
      match val.getNum? with
      | .ok n => return n.toFloat.toUInt64.toNat
      | .error e => throw (IO.userError s!"Failed to parse {key} as Nat: {e}")
  | .error e => throw (IO.userError s!"Missing key {key}: {e}")

/-- Parse a JSON number as Float -/
def jsonToFloat (j : Lean.Json) (key : String) : IO Float := do
  match j.getObjValAs? Lean.Json key with
  | .ok val =>
    match val.getNum? with
    | .ok n => return n.toFloat
    | .error _ =>
      match val.getNat? with
      | .ok n => return Float.ofNat n
      | .error e => throw (IO.userError s!"Failed to parse {key} as Float: {e}")
  | .error e => throw (IO.userError s!"Missing key {key}: {e}")

def main : IO Unit := do
  IO.println "╔══════════════════════════════════════════════════════════╗"
  IO.println "║  TTT Golden Value GPU Test                              ║"
  IO.println "╚══════════════════════════════════════════════════════════╝"
  IO.println ""

  -- Initialize WebGPU
  let inst ← Hesper.init
  let device ← getDevice inst
  IO.println "[GPU] Device initialized"

  let goldenDir := "hesper-ttt/Tests/TTT/golden-values"

  -- Load config from metadata.json
  let metadataStr ← IO.FS.readFile (goldenDir ++ "/metadata.json")
  let metadata ← match Lean.Json.parse metadataStr with
    | .ok j => pure j
    | .error e => throw (IO.userError s!"Failed to parse metadata.json: {e}")

  let hiddenDim ← jsonToNat metadata "hidden_dim"
  let vocabSize ← jsonToNat metadata "vocab_size"
  let seqLen ← jsonToNat metadata "seq_len"
  let lr ← jsonToFloat metadata "lr"
  let tau ← jsonToFloat metadata "tau"

  let config : TTTConfig := {
    hiddenDim := hiddenDim
    vocabSize := vocabSize
    innerLR := lr
    tau := tau
  }

  IO.println s!"Config: hidden_dim={hiddenDim}, vocab_size={vocabSize}, seq_len={seqLen}, lr={lr}, tau={tau}"
  IO.println ""

  -- Create GPU buffers
  let bufs ← createTTTBuffers device config
  IO.println "[GPU] Buffers allocated"

  -- Load and upload data
  IO.println "Loading golden values..."
  loadBaseWeights device bufs (goldenDir ++ "/base_weights.bin")
  let hiddenStates ← loadHiddenStates (goldenDir ++ "/hidden_states.bin") seqLen hiddenDim
  let targets ← loadTargets (goldenDir ++ "/targets.bin")

  IO.println s!"  Hidden states: {hiddenStates.size} steps x {hiddenDim} dim"
  if seqLen <= 16 then
    IO.println s!"  Targets: {targets}"
  else
    IO.println s!"  Targets: [{targets[0]!}, {targets[1]!}, {targets[2]!}, ... {targets[seqLen-1]!}] ({seqLen} tokens)"
  IO.println ""

  -- Run TTT sequence on GPU
  IO.println "Running TTT sequence on GPU..."
  let startTime ← IO.monoNanosNow
  let results ← tttSequenceGPU device config bufs hiddenStates targets
  let endTime ← IO.monoNanosNow
  let elapsedMs := (endTime - startTime).toFloat / 1000000.0
  IO.println s!"  Got {results.size} step results in {elapsedMs} ms"
  IO.println ""

  -- Validate each step against golden values
  let mut allPassed := true
  let mut failCount := (0 : Nat)
  let mut maxBaseErr := (0.0 : Float)
  let mut maxWeightErr := (0.0 : Float)
  let mut maxFinalErr := (0.0 : Float)
  let mut minCosSim := (1.0 : Float)

  let verbose := seqLen <= 16

  for t in [0:seqLen] do
    let result := results[t]!

    -- 1. Validate base logits
    let goldenBaseLogits ← loadFloatArrayFromFile (goldenDir ++ s!"/base_logits_t{t}.bin")
    let baseReport := generateReport goldenBaseLogits result.baseLogits 1e-4

    -- 2. Validate base loss
    let goldenBaseLoss ← loadFloatArrayFromFile (goldenDir ++ s!"/base_loss_t{t}.bin")
    let lossErr := Float.abs (goldenBaseLoss[0]! - result.baseLoss)

    -- 3. Validate gate decision
    let goldenGate ← loadFloatArrayFromFile (goldenDir ++ s!"/gate_decision_t{t}.bin")
    let goldenGateOpen : Bool := goldenGate[0]! > 0.5
    let gateMatch := goldenGateOpen == result.gateOpen

    -- 4. Validate TTT weights after step
    let goldenTTTWeights ← loadFloatArrayFromFile (goldenDir ++ s!"/ttt_weights_after_t{t}.bin")
    let weightReport := generateReport goldenTTTWeights result.tttWeightsAfter 1e-4

    -- 5. Validate final logits
    let goldenFinalLogits ← loadFloatArrayFromFile (goldenDir ++ s!"/final_logits_t{t}.bin")
    let finalReport := generateReport goldenFinalLogits result.finalLogits 1e-3

    -- Track worst-case metrics
    if baseReport.maxAbsError > maxBaseErr then
      maxBaseErr := baseReport.maxAbsError
    if weightReport.maxAbsError > maxWeightErr then
      maxWeightErr := weightReport.maxAbsError
    if finalReport.maxAbsError > maxFinalErr then
      maxFinalErr := finalReport.maxAbsError
    if finalReport.cosineSimilarity < minCosSim then
      minCosSim := finalReport.cosineSimilarity

    -- Check for failures
    let stepFailed := !baseReport.matchesWithinTolerance ||
      lossErr > 1e-4 || !gateMatch || !weightReport.matchesWithinTolerance ||
      finalReport.cosineSimilarity < 0.999

    if stepFailed then
      failCount := failCount + 1
      allPassed := false

    -- Print details for verbose mode, first/last steps, or failures
    let shouldPrint := verbose || t < 3 || t == seqLen - 1 || stepFailed
    if shouldPrint then
      IO.println s!"═══ Step {t} ═══"
      IO.println s!"  Base logits:  cos_sim={baseReport.cosineSimilarity}, max_err={baseReport.maxAbsError}"
      IO.println s!"  Base loss:    golden={goldenBaseLoss[0]!}, computed={result.baseLoss}, err={lossErr}"
      IO.println s!"  Gate:         golden={goldenGateOpen}, computed={result.gateOpen}, match={gateMatch}"
      IO.println s!"  TTT weights:  cos_sim={weightReport.cosineSimilarity}, max_err={weightReport.maxAbsError}"
      IO.println s!"  Final logits: cos_sim={finalReport.cosineSimilarity}, max_err={finalReport.maxAbsError}"
      if stepFailed then
        IO.println "  *** STEP FAILED ***"
      IO.println ""
    else if t == 3 && seqLen > 16 then
      IO.println s!"  ... ({seqLen - 6} steps omitted, showing first 3 + last) ..."
      IO.println ""

  -- Summary
  IO.println "═══════════════════════════════════════════════"
  IO.println s!"  Sequence length:       {seqLen}"
  IO.println s!"  Elapsed time:          {elapsedMs} ms"
  IO.println s!"  Tokens/sec:            {Float.ofNat seqLen * 1000.0 / elapsedMs}"
  IO.println s!"  Max base logit error:  {maxBaseErr}"
  IO.println s!"  Max weight error:      {maxWeightErr}"
  IO.println s!"  Max final logit error: {maxFinalErr}"
  IO.println s!"  Min cosine similarity: {minCosSim}"
  IO.println s!"  Failed steps:          {failCount} / {seqLen}"
  IO.println "═══════════════════════════════════════════════"
  IO.println ""

  IO.println "╔══════════════════════════════════════════════════════════╗"
  if allPassed then
    IO.println "║  ✓ ALL TESTS PASSED                                    ║"
  else
    IO.println "║  ✗ SOME TESTS FAILED                                   ║"
  IO.println "╚══════════════════════════════════════════════════════════╝"

  if !allPassed then
    IO.Process.exit 1
