import StubExtract.Extract

/-! # stub-extract — kernel macro 構造を grep ベースで拾う

```
lake exe stub-extract <file>                  -- ファイル内の全 kernel を dump
lake exe stub-extract <file> <fn>             -- 1 関数だけ dump
lake exe stub-extract --report <dir> <out.md> -- ディレクトリを markdown report に
```

設計方針: CUDA を transpile しない。**特徴的な行を grep して bag に詰める** だけ。
出力は (a) 関数頭の attrs / template / __launch_bounds__、(b) `__shared__` 宣言、
(c) `kbx`/`kb0`/`mmq_*`/`nwarps` を含む for-loop、(d) `__syncthreads` カウント、
(e) ホスト側の `<<<grid, block, smem, stream>>>` の中身。
-/

open Hesper.StubExtract

/-- markdown report 用ヘッダ. -/
def reportHeader (dir : String) (n : Nat) : String :=
  s!"# Kernel stub overview ({dir})\n\n" ++
  s!"Auto-generated by `lake exe stub-extract --report`.\n\n" ++
  s!"Found **{n}** interesting kernels (template / __launch_bounds__ / smem / characteristic loops / __syncthreads のいずれかを持つもの).\n\n" ++
  "Columns: `occ` = `__launch_bounds__(max_threads, min_blocks_per_sm)`. `block` = first launch site's block dim.\n\n" ++
  "## Summary\n\n" ++
  "| kernel | file | template | occ (max_thr / min_blk) | block | smem | loops | syncs | sites |\n" ++
  "|---|---|---|---|---|---|---|---|---|\n"

def buildReport (dir : String) (stubs : Array KernelStub) : String := Id.run do
  let mut out := reportHeader dir stubs.size
  -- summary table
  for s in stubs do
    let rel := s.file.replace (dir ++ "/") ""
    let s' := { s with file := rel }
    out := out ++ s'.tableRow ++ "\n"
  -- per-kernel detail (grouped by file)
  out := out ++ "\n## Per-kernel detail\n\n"
  let mut byFile : Array (String × Array KernelStub) := #[]
  for s in stubs do
    let rel := s.file.replace (dir ++ "/") ""
    match byFile.findIdx? (fun p => p.1 == rel) with
    | some i => byFile := byFile.modify i (fun (k, v) => (k, v.push { s with file := rel }))
    | none => byFile := byFile.push (rel, #[{ s with file := rel }])
  for (file, ks) in byFile do
    out := out ++ s!"### `{file}`\n\n"
    for s in ks do
      out := out ++ "```\n" ++ s.dump ++ "```\n\n"
  out

/-- 文字列 needle が haystack に substring として含まれるか. -/
def containsSubstr (haystack needle : String) : Bool :=
  match haystack.splitOn needle with
  | _ :: _ :: _ => true
  | _ => false

/-- ファイル名 (basename またはフルパス) が patterns のいずれかを substring として含むか. -/
def fileMatchesAny (file : String) (patterns : List String) : Bool :=
  patterns.any (containsSubstr file)

def main (args : List String) : IO Unit := do
  match args with
  | "--report" :: [dir, outPath] =>
    let stubs ← extractAllInDir dir
    let report := buildReport dir stubs
    IO.FS.writeFile outPath report
    IO.println s!"stub-extract: wrote {stubs.size} interesting kernels to {outPath}"
  | "--report-files" :: [dir, patternsCsv, outPath] =>
    -- Filter kernels by their source file basename. Patterns is comma-separated.
    -- interestingOnly is OFF here so pointwise kernels (im2col, pad, ...) are kept
    -- when their file is explicitly named.
    let patterns := patternsCsv.splitOn ","
    let allStubs ← extractAllInDir dir (interestingOnly := false)
    let stubs := allStubs.filter (fun s => fileMatchesAny s.file patterns)
    let report := buildReport dir stubs
    IO.FS.writeFile outPath report
    IO.println s!"stub-extract: wrote {stubs.size} kernels (filter={patternsCsv}) to {outPath}"
  | "--all" :: [dir] =>
    let stubs ← extractAllInDir dir false
    for s in stubs do IO.println s.dump
  | [file, fn] =>
    let stubs ← extractFileWithSites file
    match stubs.find? (fun s => s.name == fn) with
    | some s => IO.println s.dump
    | none =>
      IO.eprintln s!"stub-extract: kernel '{fn}' not found in {file}"
      IO.Process.exit 1
  | [file] =>
    let stubs ← extractFileWithSites file
    if stubs.isEmpty then
      IO.eprintln s!"stub-extract: no __global__ kernels found in {file}"
      IO.Process.exit 1
    for s in stubs do IO.println s.dump
  | _ =>
    IO.eprintln "usage:"
    IO.eprintln "  stub-extract <file>                              -- all kernels in file"
    IO.eprintln "  stub-extract <file> <fn>                         -- one kernel"
    IO.eprintln "  stub-extract --report <dir> <out.md>             -- interesting kernels only"
    IO.eprintln "  stub-extract --report-files <dir> P1,P2 <out.md> -- kernels in files matching P1|P2 (no interesting filter)"
    IO.eprintln "  stub-extract --all <dir>                         -- dump every kernel (no filter)"
    IO.Process.exit 2
