#!/usr/bin/env bash
# Convert tutorial Markdown masters in docs/tutorial/md/Ch*.md into
# Lean source files (.lean) and Jupyter notebooks (.ipynb) under
# docs/tutorial/Notebooks/Gen/.
#
# Requires `xlean-convert` on PATH (built from the xeus-lean project) or
# pointed at via the XLEAN_CONVERT environment variable.
#
# The generated tree is git-ignored; it is regenerated by the tutorial
# Docker image build and is not meant to be committed.

set -euo pipefail

XLEAN_CONVERT="${XLEAN_CONVERT:-xlean-convert}"

if ! command -v "${XLEAN_CONVERT}" >/dev/null 2>&1; then
  echo "error: ${XLEAN_CONVERT} not found on PATH" >&2
  echo "       build it from https://github.com/Verilean/xeus-lean and" >&2
  echo "       either install it or set XLEAN_CONVERT=/path/to/xlean-convert" >&2
  exit 1
fi

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SRC_DIR="${ROOT}/docs/tutorial/md"
OUT_LEAN_DIR="${ROOT}/docs/tutorial/Notebooks/Gen"
OUT_IPYNB_DIR="${ROOT}/docs/tutorial/Notebooks/Gen/notebooks"

mkdir -p "${OUT_LEAN_DIR}" "${OUT_IPYNB_DIR}"

shopt -s nullglob
for src in "${SRC_DIR}"/Ch*.md; do
  base="$(basename "${src}" .md)"
  # Ch00_Setup → ch00-setup
  ipynb_name="$(echo "${base}" | tr '[:upper:]_' '[:lower:]-')"

  out_lean="${OUT_LEAN_DIR}/${base}.lean"
  out_ipynb="${OUT_IPYNB_DIR}/${ipynb_name}.ipynb"

  echo "[build-from-md] ${base}"
  "${XLEAN_CONVERT}" --to lean  "${src}" -o "${out_lean}"
  "${XLEAN_CONVERT}" --to ipynb "${src}" -o "${out_ipynb}"
done

echo "[build-from-md] done — outputs in ${OUT_LEAN_DIR}"
